version: "3.10"
services:

  selenium-hub-II:
    image: selenium/hub:latest
    container_name: seleniumHub-openWa-II
    ports:
      - "4446:4444"
    volumes:
      - mydata:/app/data
  


  ChromeService:
    image: selenium/node-chrome:latest
    shm_size: "2gb"
    ports:
      - "5906"  
      - "7906"
    environment:
      - SE_EVENT_BUS_HOST=seleniumHub-openWa-II
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=3
    depends_on:
      - selenium-hub-II
  
  whatsapp-web-II:
    build: .
    ports:
      - "8086:8086"
    depends_on:
      - selenium-hub-II
    volumes:
      - mydata:/app/data

volumes:
  mydata: