version: "3.10"
services:

  selenium-hub:
    image: selenium/hub:latest
    container_name: seleniumHub-openWa
    ports:
      - "4449:4444"
    volumes:
      - mydata:/app/data
  


  ChromeService:
    image: selenium/node-chrome:latest
    shm_size: "2gb"
    ports:
      - "5909"  
      - "7909"
    environment:
      - SE_EVENT_BUS_HOST=seleniumHub-openWa
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=3
    depends_on:
      - selenium-hub
  
  whatsapp-web:
    build: .
    ports:
      - "8089:8089"
    depends_on:
      - selenium-hub
    volumes:
      - mydata:/app/data

volumes:
  mydata: